### ISSUE TITLE
chore: Update Hexa.NET.ImGui to the latest

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-community-toolkit#177]
Not urgent. There is some error when upgrading to 2.2.2.

**Comment by Doprez** [comment]
That is a strange issue, it seems to be complaining about a empty ID for a window but it seems like it should be there and is not empty...

Checking the below line, it clearly shows that it has the name of the relevant created `BaseWindow`.
https://github.com/stride3d/stride-community-toolkit/blob/e772e56190325e4de07763d03eac0d158181d234/src/Stride.CommunityToolkit.ImGui/ImGuiExtension.cs#L83

error:
```
Assertion failed: id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!", 
file D:\a\Hexa.NET.ImGui\Hexa.NET.ImGui\cimgui\imgui\imgui.cpp, line 11416
```

Not sure what I'm missing here.

**Comment by VaclavElias** [comment]
Latest update to 2.2.4, the same error:

`Assertion failed: id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!", file D:\a\Hexa.NET.ImGui\Hexa.NET.ImGui\cimgui\imgui\imgui.cpp, line 11471
`

**Comment by VaclavElias** [comment]
@Doprez, some updates for you 🙂 https://github.com/HexaEngine/Hexa.NET.ImGui/issues/33

**Comment by Doprez** [comment]
Well the good news is that the update pointed out a few issues that were apparently in the system. I have some work around fixes for now but there are definitely areas to improve.

**Comment by VaclavElias** [comment]
I love how other libraries` contributors are helping 🙂
