### ISSUE TITLE
MeshBuilder to generate procedural meshes with custom components

### ISSUE THREAD

**Issue by dotlogix** [stride3d/stride-community-toolkit#47]
Hey there for one of my projects I created a mesh builder class capable of creating mesh draw instances on the fly with arbitrary VertexElement declarations.

I wonder if this would be a good fit for this project. The API looks like this:

``` csharp
using var builder = new MeshBuilder();
builder.WithIndexType(IndexType.Int32);
builder.WithPrimitiveType(PrimitiveType.TriangleList);

var position = builder.WithPosition<Vector3>();
var color = builder.WithColor<Color>();
var normal = builder.WithNormal<Vector3>();

builder.BeginVertex();
builder.SetElement(position, new Vector3(0, 0, 0));
builder.SetElement(color, new Color(255,0,0));
builder.SetElement(normal, Vector3.UnitY);

builder.BeginVertex();
builder.SetElement(position, new Vector3(0, 0, 100));
builder.SetElement(color, new Color(0,255,0));
builder.SetElement(normal, Vector3.UnitY);

builder.BeginVertex();
builder.SetElement(position, new Vector3(100, 0, 100));
builder.SetElement(color, new Color(0,0,255));
builder.SetElement(normal, Vector3.UnitY);

builder.AddIndex(0);
builder.AddIndex(2);
builder.AddIndex(1);

var meshDraw = builder.ToMeshDraw(GraphicsDevice, false);
```

This example would create a simple triangle with Position, Normal and Color

**Comment by VaclavElias** [comment]
@Doprez and @IXLLEGACYIXL, I am not that far to understand this subject except I wanted to create some shapes a few months ago.. Would this be a good addition?

**Comment by VaclavElias** [comment]
@dotlogix, would you be ok to add also some manual, how to use it + examples? I am trying to figure out how to structure the Manual for the toolkit https://stride3d.github.io/stride-community-toolkit/manual/index.html. I can do for you formatting and styling but I would just need content.

**Comment by Doprez** [comment]
This could deinitely be a handy addition. I am not well versed in graphics though I usually turn to Tebjan or Youness for help on that. 

I could personally use this to generate a mesh for https://github.com/ikpil/DotRecast to show the navmesh when I need it.

**Comment by VaclavElias** [comment]
I saw on Discord that it is liked. Anyway, let's get it in because then we can add it also to our examples and see how it makes our life easier 🙂

**Comment by dotlogix** [comment]
@VaclavElias any suggestion where to put it then I could open a PR and also include some examples

**Comment by VaclavElias** [comment]
As you might know, toolkit is under development so things might be moved around. I think the right location should be in the folder `Rendering` https://github.com/stride3d/stride-community-toolkit/tree/main/src/Stride.CommunityToolkit/Rendering, you can decide the structure for now, however you think it is appropriate.

Regarding the docs, we should create also a new section `Rendering`? What do you think?

![image](https://github.com/stride3d/stride-community-toolkit/assets/4528464/ab773dc7-f50a-4147-b2f3-49ac24caf9d1)

**Comment by dotlogix** [comment]
So i added a PR for the mesh builder including a couple of simple examples.
However as I just started using stride basically yesterday I am stills tuggeling with the basics like how to map materials and stuff and would like to request support from one of you.

I would love to contribute the documentation as well but as you see it is difficult for me because I also don't know how to do it 😄

**Comment by Doprez** [comment]
Ill tag @tebjan and @ykafia for the rendering questions since I am pretty ignorant in that regard. a few resources you can look at are the terrain examples in https://github.com/Doprez/Awesome-Stride#terrain and the shaders in https://github.com/Doprez/Awesome-Stride#shaders they may be able to help point you in the right direction.

For the docs you can modify the pages [here](https://github.com/stride3d/stride-community-toolkit/tree/main/docs) they should be in a similar format to markdown and they are in a constant state of change so dont worry about any mistakes. This repo is meant to be used as a sort of testing grounds so even just [example projects](https://github.com/stride3d/stride-community-toolkit/blob/main/examples/code-only/Example04_MyraUI/MainView.cs) with some comments is a great start.

**Comment by VaclavElias** [comment]
I am actually working on that, added it also to our docs. I will comment shortly with more details. Thank you @dotlogix

**Comment by VaclavElias** [comment]
Hello, I have published updated docs and a new NuGet is being deployed.

You can see the docs here
https://stride3d.github.io/stride-community-toolkit/manual/code-only/examples/procedural-geometry.html

@dotlogix, if you would like, you can add more content. You can see the other examples what content is added. Be it just more description on the top. Or you can go even deeper.

Also, if you would like you can add later/in the future more examples. Maybe some interaction or/and animation.

Also, feel free to come back with further updates or code improvements, not only with your addition but anything.

Thank you.
